Fix NoSuchMethodError when disabling Netty. Fixes #793
When Netty is disabled (-Dorg.spigotmc.netty.disabled=true), MCPC+ would
crash on client connect with:
    java.lang.NoSuchMethodError: org.bouncycastle.crypto.BufferedBlockCipher.a(ZLorg/bouncycastle/crypto/CipherParameters;)V
due to using the obfuscated Bouncycastle mappings. Remove the appropriate
mappings so that the vanilla network manager will use Forge's Bouncycastle,
therefore finding the correct method (with the non-obfuscated name).