Fix NPE when adding vanilla ore to Forge block orebfuscator list during static initialization
Forge now adds the vanilla ores to the OreDictionary, which MCPC+ adds
to the "Forge ore block" list for Spigot orebfuscator. Reorder the
initialization so the list is created properly before adding the ores.

Fixes:
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class net.minecraftforge.oredict.OreDictionary
(which masks an NPE on forgeOreBlocks)
https://gist.github.com/agaricusb/5473893