Preload world crash report to unmask the real crash. Fixes #721.
Crashes from out of memory or StackOverflow can be masked by
NoClassDefFoundErrors, since the crash report classes
(CallableLvl1 and others) cannot be loaded. To solve this,
synthesize a dummy crash report on first world load.

This augments the Forge patch:
MinecraftForge/MinecraftForge@9a72d50dec7520d1d88551cba4e3aeaf3e606070 Early define CrashReport classes to combat invalid crash details.
which preloads most of the crash classes, but this commit also
preloads the world-specific crash report classes.